// gists/1c5562442e51ef507aee4d2421f9ad27/apps/react/src/CheckFirst.tsx
import { add, getOptions, remove, type State } from "shared"

const CheckFirst = ({ state, onChange }: { state: State; onChange: (state: State) => void }) => {
	const list = getOptions()

	const _onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		const { type, value, checked } = event.target

		if (type === "checkbox") {
			if (checked) {
				onChange({
					checks: add(state.checks, value),
					radio: state.radio == null ? value : state.radio,
				})
			} else {
				onChange({
					checks: remove(state.checks, value),
					radio: state.radio === value ? null : state.radio,
				})
			}
		} else {
			onChange({ ...state, radio: value })
		}
	}

	return (
		<section onChange={_onChange}>
			{list.map((item) => {
				const checked = state.checks.includes(item.id)
				const radio = state.radio === item.id
				return (
					<div className="row" key={item.id}>
						<input type="checkbox" checked={checked} value={item.id} />
						<input type="radio" checked={radio} disabled={!checked} value={item.id} />
						<label>{item.label}</label>
					</div>
				)
			})}
		</section>
	)
}

export default CheckFirst

// gists/1c5562442e51ef507aee4d2421f9ad27/apps/lit/src/check-first.ts
import { LitElement, html } from "lit"
import { customElement, property } from "lit/decorators.js"
import { getOptions, add, remove, type State } from "shared"

@customElement("check-first")
export class CheckFirst extends LitElement {
	// Shadow DOM を無効化
	protected createRenderRoot() {
		return this
	}

	@property({ attribute: false })
	state!: State

	private onChange(event: Event) {
		const { type, value, checked } = event.target as HTMLInputElement

		if (type === "checkbox") {
			if (checked) {
				this.dispatchEvent(
					new CustomEvent("state-change", {
						detail: {
							checks: add(this.state.checks, value),
							radio: this.state.radio == null ? value : this.state.radio,
						},
						bubbles: true,
					}),
				)
			} else {
				this.dispatchEvent(
					new CustomEvent("state-change", {
						detail: {
							checks: remove(this.state.checks, value),
							radio: this.state.radio === value ? null : this.state.radio,
						},
						bubbles: true,
					}),
				)
			}
		} else {
			this.dispatchEvent(
				new CustomEvent("state-change", {
					detail: {
						...this.state,
						radio: value,
					},
					bubbles: true,
				}),
			)
		}
	}

	render() {
		const list = getOptions()

		return html`
			<section @change=${this.onChange}>
				${list.map((item) => {
					const checked = this.state.checks.includes(item.id)
					const radio = this.state.radio === item.id
					return html`
						<div class="row">
							<input type="checkbox" .checked=${checked} .value=${item.id} />
							<input
								type="radio"
								.checked=${radio}
								.disabled=${!checked}
								.value=${item.id}
							/>
							<label>${item.label}</label>
						</div>
					`
				})}
			</section>
		`
	}
}

declare global {
	interface HTMLElementTagNameMap {
		"check-first": CheckFirst
	}
}
