// gists/1c5562442e51ef507aee4d2421f9ad27/apps/angular/src/radio-first/radio-first.ts
import { Component, input, output } from "@angular/core"
import { getOptions, add, remove, type State } from "shared"

@Component({
	selector: "radio-first",
	templateUrl: "./radio-first.html",
})
export class RadioFirst {
	readonly state = input.required<State>()
	readonly state_change = output<State>()

	protected readonly list = getOptions()

	protected isChecked(item: { id: string }): boolean {
		return this.state().checks.includes(item.id)
	}

	protected isRadio(item: { id: string }): boolean {
		return this.state().radio === item.id
	}

	protected onChange(event: Event) {
		const { type, value, checked } = event.target as HTMLInputElement

		if (type === "radio") {
			this.state_change.emit({
				radio: value,
				checks: add(this.state().checks, value),
			})
		} else {
			this.state_change.emit({
				...this.state(),
				checks: checked
					? add(this.state().checks, value)
					: remove(this.state().checks, value),
			})
		}
	}
}

// gists/1c5562442e51ef507aee4d2421f9ad27/apps/stencil/src/components/radio-first/radio-first.tsx
import { Event, Component, EventEmitter, Host, Prop, h } from "@stencil/core"
import { getOptions, add, remove, type State } from "shared"

@Component({
	tag: "radio-first",
})
export class RadioFirst {
	@Prop() state!: State
	@Event() changeState!: EventEmitter<State>

	private onChange = (event: Event) => {
		const { type, value, checked } = event.target as HTMLInputElement

		if (type === "radio") {
			this.changeState.emit({
				radio: value,
				checks: add(this.state.checks, value),
			})
		} else {
			this.changeState.emit({
				...this.state,
				checks: checked ? add(this.state.checks, value) : remove(this.state.checks, value),
			})
		}
	}

	render() {
		const list = getOptions()

		return (
			<Host>
				<section onChange={this.onChange}>
					{list.map((item) => {
						const checked = this.state.checks.includes(item.id)
						const radio = this.state.radio === item.id
						return (
							<div class="row">
								<input type="radio" checked={radio} value={item.id} />
								<input
									type="checkbox"
									checked={checked}
									disabled={radio}
									value={item.id}
								/>
								<label>{item.label}</label>
							</div>
						)
					})}
				</section>
			</Host>
		)
	}
}
