// gists/1c5562442e51ef507aee4d2421f9ad27/apps/react/src/App.tsx
import { useEffect, useState } from "react"
import CheckFirst from "./CheckFirst.tsx"
import RadioFirst from "./RadioFirst.tsx"
import { prepareSW, load, save, type State } from "shared"

const App = () => {
	const [state, setState] = useState<State>()

	useEffect(() => {
		prepareSW("../sw.js")
			.then(async () => {
				const data = await load("../api")
				setState(data)
			})
			.catch((err) => {
				console.error(err)
				alert("エラーが発生しました")
			})
	}, [])

	const onChange = async (state: State) => {
		setState(state)
		await save("../api", state)
	}

	const onClear = async () => {
		await onChange({
			checks: [],
			radio: null,
		})
	}

	if (state == null) {
		return <div>Loading...</div>
	}

	return (
		<div>
			<header>
				<h1>React</h1>
				<button onClick={onClear}>クリア</button>
			</header>
			<main>
				<CheckFirst state={state} onChange={onChange} />
				<RadioFirst state={state} onChange={onChange} />
			</main>
		</div>
	)
}

export default App

// gists/1c5562442e51ef507aee4d2421f9ad27/apps/vue/src/App.tsx
import { onMounted, ref, type Ref } from "vue"
import { prepareSW, load, save, type State } from "shared"
import CheckFirst from "./CheckFirst.tsx"
import RadioFirst from "./RadioFirst.tsx"

const App = () => {
	const state = ref<State>()

	onMounted(() => {
		prepareSW("../sw.js")
			.then(async () => {
				const data = await load("../api")
				state.value = data
			})
			.catch((err) => {
				console.error(err)
				alert("エラーが発生しました")
			})
	})

	const onChange = async (new_state: State) => {
		state.value = new_state
		await save("../api", new_state)
	}

	const onClear = async () => {
		await onChange({
			checks: [],
			radio: null,
		})
	}

	return (
		<>
			{state.value == null ? (
				<div>Loading...</div>
			) : (
				<div>
					<header>
						<h1>Vue</h1>
						<button onClick={onClear}>クリア</button>
					</header>
					<main>
						<CheckFirst state={state as Ref<State>} onStateChange={onChange} />
						<RadioFirst state={state as Ref<State>} onStateChange={onChange} />
					</main>
				</div>
			)}
		</>
	)
}

export default App
