// gists/1c5562442e51ef507aee4d2421f9ad27/apps/react/src/CheckFirst.tsx
import { add, getOptions, remove, type State } from "shared"

const CheckFirst = ({ state, onChange }: { state: State; onChange: (state: State) => void }) => {
	const list = getOptions()

	const _onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		const { type, value, checked } = event.target

		if (type === "checkbox") {
			if (checked) {
				onChange({
					checks: add(state.checks, value),
					radio: state.radio == null ? value : state.radio,
				})
			} else {
				onChange({
					checks: remove(state.checks, value),
					radio: state.radio === value ? null : state.radio,
				})
			}
		} else {
			onChange({ ...state, radio: value })
		}
	}

	return (
		<section onChange={_onChange}>
			{list.map((item) => {
				const checked = state.checks.includes(item.id)
				const radio = state.radio === item.id
				return (
					<div className="row" key={item.id}>
						<input type="checkbox" checked={checked} value={item.id} />
						<input type="radio" checked={radio} disabled={!checked} value={item.id} />
						<label>{item.label}</label>
					</div>
				)
			})}
		</section>
	)
}

export default CheckFirst

// gists/1c5562442e51ef507aee4d2421f9ad27/apps/stencil/src/components/check-first/check-first.tsx
import { Event, Component, EventEmitter, Host, Prop, h } from "@stencil/core"
import { getOptions, add, remove, type State } from "shared"

@Component({
	tag: "check-first",
})
export class CheckFirst {
	@Prop() state!: State
	@Event() changeState!: EventEmitter<State>

	private onChange = (event: Event) => {
		const { type, value, checked } = event.target as HTMLInputElement

		if (type === "checkbox") {
			if (checked) {
				this.changeState.emit({
					checks: add(this.state.checks, value),
					radio: this.state.radio == null ? value : this.state.radio,
				})
			} else {
				this.changeState.emit({
					checks: remove(this.state.checks, value),
					radio: this.state.radio === value ? null : this.state.radio,
				})
			}
		} else {
			this.changeState.emit({
				...this.state,
				radio: value,
			})
		}
	}

	render() {
		const list = getOptions()

		return (
			<Host>
				<section onChange={this.onChange}>
					{list.map((item) => {
						const checked = this.state.checks.includes(item.id)
						const radio = this.state.radio === item.id
						return (
							<div class="row">
								<input type="checkbox" checked={checked} value={item.id} />
								<input
									type="radio"
									checked={radio}
									disabled={!checked}
									value={item.id}
								/>
								<label>{item.label}</label>
							</div>
						)
					})}
				</section>
			</Host>
		)
	}
}
