// gists/1c5562442e51ef507aee4d2421f9ad27/apps/angular/src/app/app.ts
import { Component, OnInit, signal } from "@angular/core"
import { prepareSW, load, save, type State } from "shared"
import { CheckFirst } from "../check-first/check-first"
import { RadioFirst } from "../radio-first/radio-first"

@Component({
	selector: "app-root",
	templateUrl: "./app.html",
	imports: [CheckFirst, RadioFirst],
})
export class App implements OnInit {
	protected readonly state = signal<State | null>(null)

	ngOnInit() {
		void this.init()
	}

	private async init() {
		try {
			await prepareSW("../sw.js")
			const data = await load("../api")
			this.state.set(data)
		} catch (err) {
			console.error(err)
			alert("エラーが発生しました")
		}
	}

	protected async updateState(state: State): Promise<void> {
		this.state.set(state)
		await save("../api", state)
	}

	protected async onClear(): Promise<void> {
		await this.updateState({
			checks: [],
			radio: null,
		})
	}
}

// gists/1c5562442e51ef507aee4d2421f9ad27/apps/react/src/App.tsx
import { useEffect, useState } from "react"
import CheckFirst from "./CheckFirst.tsx"
import RadioFirst from "./RadioFirst.tsx"
import { prepareSW, load, save, type State } from "shared"

const App = () => {
	const [state, setState] = useState<State>()

	useEffect(() => {
		prepareSW("../sw.js")
			.then(async () => {
				const data = await load("../api")
				setState(data)
			})
			.catch((err) => {
				console.error(err)
				alert("エラーが発生しました")
			})
	}, [])

	const onChange = async (state: State) => {
		setState(state)
		await save("../api", state)
	}

	const onClear = async () => {
		await onChange({
			checks: [],
			radio: null,
		})
	}

	if (state == null) {
		return <div>Loading...</div>
	}

	return (
		<div>
			<header>
				<h1>React</h1>
				<button onClick={onClear}>クリア</button>
			</header>
			<main>
				<CheckFirst state={state} onChange={onChange} />
				<RadioFirst state={state} onChange={onChange} />
			</main>
		</div>
	)
}

export default App
