// gists/1c5562442e51ef507aee4d2421f9ad27/apps/stencil/src/components/radio-first/radio-first.tsx
import { Event, Component, EventEmitter, Host, Prop, h } from "@stencil/core"
import { getOptions, add, remove, type State } from "shared"

@Component({
	tag: "radio-first",
})
export class RadioFirst {
	@Prop() state!: State
	@Event() changeState!: EventEmitter<State>

	private onChange = (event: Event) => {
		const { type, value, checked } = event.target as HTMLInputElement

		if (type === "radio") {
			this.changeState.emit({
				radio: value,
				checks: add(this.state.checks, value),
			})
		} else {
			this.changeState.emit({
				...this.state,
				checks: checked ? add(this.state.checks, value) : remove(this.state.checks, value),
			})
		}
	}

	render() {
		const list = getOptions()

		return (
			<Host>
				<section onChange={this.onChange}>
					{list.map((item) => {
						const checked = this.state.checks.includes(item.id)
						const radio = this.state.radio === item.id
						return (
							<div class="row">
								<input type="radio" checked={radio} value={item.id} />
								<input
									type="checkbox"
									checked={checked}
									disabled={radio}
									value={item.id}
								/>
								<label>{item.label}</label>
							</div>
						)
					})}
				</section>
			</Host>
		)
	}
}

// gists/1c5562442e51ef507aee4d2421f9ad27/apps/react/src/RadioFirst.tsx
import { getOptions, add, remove, type State } from "shared"

const RadioFirst = ({ state, onChange }: { state: State; onChange: (state: State) => void }) => {
	const list = getOptions()

	const _onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
		const { type, value, checked } = event.target

		if (type === "radio") {
			onChange({
				radio: value,
				checks: add(state.checks, value),
			})
		} else {
			onChange({
				...state,
				checks: checked ? add(state.checks, value) : remove(state.checks, value),
			})
		}
	}

	return (
		<section onChange={_onChange}>
			{list.map((item) => {
				const checked = state.checks.includes(item.id)
				const radio = state.radio === item.id
				return (
					<div className="row" key={item.id}>
						<input type="radio" checked={radio} value={item.id} />
						<input type="checkbox" checked={checked} disabled={radio} value={item.id} />
						<label>{item.label}</label>
					</div>
				)
			})}
		</section>
	)
}

export default RadioFirst
