// gists/1c5562442e51ef507aee4d2421f9ad27/apps/stencil/src/components/check-first/check-first.tsx
import { Event, Component, EventEmitter, Host, Prop, h } from "@stencil/core"
import { getOptions, add, remove, type State } from "shared"

@Component({
	tag: "check-first",
})
export class CheckFirst {
	@Prop() state!: State
	@Event() changeState!: EventEmitter<State>

	private onChange = (event: Event) => {
		const { type, value, checked } = event.target as HTMLInputElement

		if (type === "checkbox") {
			if (checked) {
				this.changeState.emit({
					checks: add(this.state.checks, value),
					radio: this.state.radio == null ? value : this.state.radio,
				})
			} else {
				this.changeState.emit({
					checks: remove(this.state.checks, value),
					radio: this.state.radio === value ? null : this.state.radio,
				})
			}
		} else {
			this.changeState.emit({
				...this.state,
				radio: value,
			})
		}
	}

	render() {
		const list = getOptions()

		return (
			<Host>
				<section onChange={this.onChange}>
					{list.map((item) => {
						const checked = this.state.checks.includes(item.id)
						const radio = this.state.radio === item.id
						return (
							<div class="row">
								<input type="checkbox" checked={checked} value={item.id} />
								<input
									type="radio"
									checked={radio}
									disabled={!checked}
									value={item.id}
								/>
								<label>{item.label}</label>
							</div>
						)
					})}
				</section>
			</Host>
		)
	}
}

// gists/1c5562442e51ef507aee4d2421f9ad27/apps/angular/src/check-first/check-first.ts
import { Component, input, output } from "@angular/core"
import { getOptions, add, remove, type State } from "shared"

@Component({
	selector: "check-first",
	templateUrl: "./check-first.html",
})
export class CheckFirst {
	readonly state = input.required<State>()
	readonly state_change = output<State>()

	protected readonly list = getOptions()

	protected isChecked(item: { id: string }): boolean {
		return this.state().checks.includes(item.id)
	}

	protected isRadio(item: { id: string }): boolean {
		return this.state().radio === item.id
	}

	protected onChange(event: Event) {
		const { type, value, checked } = event.target as HTMLInputElement

		if (type === "checkbox") {
			if (checked) {
				this.state_change.emit({
					checks: add(this.state().checks, value),
					radio: this.state().radio == null ? value : this.state().radio,
				})
			} else {
				this.state_change.emit({
					checks: remove(this.state().checks, value),
					radio: this.state().radio === value ? null : this.state().radio,
				})
			}
		} else {
			this.state_change.emit({
				...this.state(),
				radio: value,
			})
		}
	}
}
